apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: skypower-test
  labels:
    strimzi.io/cluster: skyfri-development
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
