apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: skypower-1
  labels:
    strimzi.io/cluster: skyfri-development
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic my-topic using consumer group my-group
      - resource:
          type: topic
          name: skypower-test
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: skypower-test
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: skypower-group-1
          patternType: literal
        operation: Read
        host: "*"
      # Example Producer Acls for topic my-topic
      - resource:
          type: topic
          name: skypower-test
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: skypower-test
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: skypower-test
          patternType: literal
        operation: Describe
        host: "*"
